### ISSUE TITLE
Investigate enabling Corbetura

### ISSUE THREAD

**Issue by sfloess** [solenopsis/Keraiai#27]
For some reason when we instrument using Corbetura upstream in [FlossWare jCore](https://github.com/FlossWare/jCore) yield ClassNotFoundException's:
```
org.solenopsis.keraiai.credentials.AbstractCredentialsTest
test_getSecurityPassword_blankPassword(org.solenopsis.keraiai.credentials.AbstractCredentialsTest)  Time elapsed: 0.012 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalArgumentException> but was<java.lang.NoClassDefFoundError>
	at org.solenopsis.keraiai.credentials.AbstractCredentialsTest.test_getSecurityPassword_blankPassword(AbstractCredentialsTest.java:203)
Caused by: java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.TouchCollector
	at org.solenopsis.keraiai.credentials.AbstractCredentialsTest.test_getSecurityPassword_blankPassword(AbstractCredentialsTest.java:203)
```
My initial suspicion is the configration/goal sections of the pom.xml.

This is related to [FlossWare jCore issue 47](https://github.com/FlossWare/jCore/issues/47).

**Comment by sfloess** [comment]
This was just fixed.  Had the wrong lifecycle in place (was kicking off for clean).
